name: Build and Test

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
        path: v

    - name: Checkout Coreutils
      uses: actions/checkout@v2
      with:
        path: libsodium

    - name: Install libsodium-dev package
      run: sudo apt-get install --quiet -y libsodium-dev

    - name: Build V
      run: cd v && make && sudo ./v symlink && cd -

    - name: V doctor
      run: v doctor

    - name: Symlink libsodium to ~/.vmodules
      run: ln -s $(pwd)/libsodium ~/.vmodules/libsodium

    - name: Ensure everything is formatted
      run: v fmt -verify ~/.vmodules/libsodium

    - name: Run tests
      run: v test ~/.vmodules/libsodium

    - name: Build example
      run: v -cstrict ~/.vmodules/libsodium/examples/example.v

    - name: Build example with -prod
      run: v -cc clang -cstrict -prod ~/.vmodules/libsodium/examples/example.v
